FROM rust:1.63-alpine3.16 as builder

COPY . .
RUN apk add alpine-sdk
RUN cargo test
RUN cargo build --release

FROM debian:buster-slim as runner
RUN apt-get update && \
    apt-get install -y dumb-init && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/

COPY --from=builder ./target/release/client /usr/local/bin
RUN chmod +x /usr/local/bin/client

ENV PATH /resources/wow
ENV PORT 7373

ENTRYPOINT ["/usr/bin/dumb-init","--"]
CMD ["client"]